export function fmtAED(v) {
  if (!v || isNaN(v)) return "AED 0.00";
  if (Math.abs(v) < 0.01) v = 0;
  let n = parseFloat(v) || 0;
  if (Math.abs(n) < 0.001) n = 0;
  const s = n.toFixed(2);
  const parts = s.split('.');
  parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, ',');
  return 'AED ' + parts.join('.');
}

export function escHtml(str) {
  if (!str) return '';
  const d = document.createElement('div');
  d.appendChild(document.createTextNode(str));
  return d.innerHTML;
}

export function sendWhatsApp(phone, name, remaining) {
  if (!phone) {
    alert('No phone number saved for this student.');
    return;
  }
  const msg = 'مرحباً ' + name + '، أرجو العلم أن إجمالي الحصص المستحقة هذا الشهر هو ' + remaining.toFixed(2) + ' درهم، شاكرين ومقدرين التزامكم.';
  const cleanPhone = phone.replace(/[\s\+]/g, '');
  window.open('https://wa.me/' + cleanPhone + '?text=' + encodeURIComponent(msg), '_blank');
}

export function generateInvoice(studentId) {
  fetch('/api/students/' + studentId + '/sessions')
    .then(r => r.json())
    .then(data => {
      const student = data.student;
      const sessions = data.sessions;
      let totalDue = 0, totalPaid = 0;
      sessions.forEach(s => { totalDue += parseFloat(s.amount_due); totalPaid += parseFloat(s.amount_paid); });
      const remaining = totalDue - totalPaid;

      const rows = sessions.map((s, i) => {
        const bal = parseFloat(s.amount_due) - parseFloat(s.amount_paid);
        return [
          (i + 1).toString(),
          s.session_date || '---',
          s.subject || '---',
          s.hours + 'h ' + s.minutes + 'm',
          fmtAED(s.amount_due),
          fmtAED(s.amount_paid),
          fmtAED(bal)
        ];
      });

      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();
      const pageW = doc.internal.pageSize.getWidth();

      doc.setTextColor(0, 0, 0);
      doc.setFontSize(16);
      doc.text('Statement of Account', pageW / 2, 20, { align: 'center' });
      doc.setFontSize(10);
      doc.text(new Date().toLocaleDateString(), pageW / 2, 27, { align: 'center' });
      doc.setFontSize(12);
      doc.text('Student: ' + student.name, 14, 38);

      doc.autoTable({
        startY: 45,
        theme: 'grid',
        head: [['#', 'Date', 'Subject', 'Time', 'Due', 'Paid', 'Balance']],
        body: rows,
        foot: [[
          { content: 'Totals', colSpan: 4, styles: { halign: 'right', fontStyle: 'bold' } },
          { content: fmtAED(totalDue), styles: { halign: 'right', fontStyle: 'bold' } },
          { content: fmtAED(totalPaid), styles: { halign: 'right', fontStyle: 'bold' } },
          { content: fmtAED(remaining), styles: { halign: 'right', fontStyle: 'bold', textColor: remaining > 0 ? [220, 53, 69] : [40, 167, 69] } }
        ]],
        styles: { textColor: [0, 0, 0], fontSize: 10, cellPadding: 4 },
        headStyles: { fillColor: [40, 40, 40], textColor: [255, 255, 255], fontStyle: 'bold', halign: 'center' },
        bodyStyles: { halign: 'center' },
        alternateRowStyles: { fillColor: [245, 245, 245] },
        footStyles: { fillColor: [220, 220, 220], textColor: [0, 0, 0], fontStyle: 'bold', halign: 'right' },
        columnStyles: { 0: { cellWidth: 10 }, 1: { cellWidth: 25 }, 3: { cellWidth: 22 }, 4: { halign: 'right', cellWidth: 25 }, 5: { halign: 'right', cellWidth: 25 }, 6: { halign: 'right', cellWidth: 25 } }
      });

      const finalY = doc.lastAutoTable.finalY || 150;
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(8);
      doc.text("Generated by Yazan's Personal Finance App", pageW / 2, finalY + 15, { align: 'center' });
      doc.save('Statement_' + student.name.replace(/\s+/g, '_') + '.pdf');
    })
    .catch(err => console.error(err));
}
